import { useEffect, useState } from 'react'
import { api } from '../services/api'
import type { Dashboard, Order, OrderStatus } from '../types/api'
import type { DistributionPoint } from '../types/distributionPoint'
import type { Product } from '../types/product'
type AdminDashboardProps = { credentials: string; points: DistributionPoint[]; products: Product[]; onLogout: () => void }
const statuses: { value: OrderStatus; label: string }[] = [{ value: 'RECEIVED', label: 'התקבלה' }, { value: 'PREPARING', label: 'בהכנה' }, { value: 'READY_FOR_PICKUP', label: 'מוכנה לאיסוף' }, { value: 'DELIVERED', label: 'נמסרה' }, { value: 'CANCELLED', label: 'בוטלה' }]
export function AdminDashboard({ credentials, points, products, onLogout }: AdminDashboardProps) {
 const [orders,setOrders]=useState<Order[]>([]); const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [filters,setFilters]=useState({pickupPointId:'',productId:'',customerQuery:'',packed:'',status:''}); const [error,setError]=useState(''); const [loading,setLoading]=useState(true)
 async function load(){setLoading(true);setError('');try{const[nextOrders,nextDashboard]=await Promise.all([api.adminOrders(credentials,filters),api.dashboard(credentials,filters.pickupPointId)]);setOrders(nextOrders);setDashboard(nextDashboard)}catch{setError('לא ניתן לטעון את נתוני הניהול. בדקי את פרטי הכניסה ואת השרת.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 async function save(order:Order,status:OrderStatus,packed:boolean,adminNote:string){try{await api.updateOrder(credentials,order.id,status,packed,adminNote);await load()}catch{setError('שמירת ההזמנה נכשלה.')}}
 return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">ניהול משק 32</p><h1>הזמנות ומאזן</h1></div><button className="button button--secondary" onClick={onLogout}>התנתקות</button></header>{dashboard&&<section className="admin-stats"><div><span>הזמנות</span><strong>{dashboard.totalOrders}</strong></div><div><span>נארזו</span><strong>{dashboard.packedOrders}</strong></div><div><span>פתוחות</span><strong>{dashboard.openOrders}</strong></div><div><span>סך הזמנות</span><strong>₪{dashboard.totalRevenue}</strong></div></section>}<section className="admin-filters"><label>נקודת איסוף<select value={filters.pickupPointId} onChange={(e)=>setFilters({...filters,pickupPointId:e.target.value})}><option value="">הכול</option>{points.map(point=><option key={point.id} value={point.id}>{point.locality} — {point.name}</option>)}</select></label><label>מוצר<select value={filters.productId} onChange={(e)=>setFilters({...filters,productId:e.target.value})}><option value="">הכול</option>{products.map(product=><option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>לקוח או טלפון<input value={filters.customerQuery} onChange={(e)=>setFilters({...filters,customerQuery:e.target.value})}/></label><label>אריזה<select value={filters.packed} onChange={(e)=>setFilters({...filters,packed:e.target.value})}><option value="">הכול</option><option value="true">נארז</option><option value="false">לא נארז</option></select></label><button className="button button--primary" onClick={()=>void load()}>סינון</button></section>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<p>טוען הזמנות…</p>:<section className="admin-orders">{orders.length===0?<p>לא נמצאו הזמנות לפי הסינון שבחרת.</p>:orders.map(order=><AdminOrder key={order.id} order={order} onSave={save}/>)}</section>}{dashboard&&dashboard.byPickupPoint.length>0&&<section className="pickup-summary"><h2>מאזן לפי נקודת איסוף</h2>{dashboard.byPickupPoint.map(point=><div key={point.distributionPointId}><span>{point.distributionPointName}</span><span>{point.orders} הזמנות · ₪{point.revenue}</span></div>)}</section>}</main>
}
function AdminOrder({order,onSave}:{order:Order;onSave:(order:Order,status:OrderStatus,packed:boolean,note:string)=>void}){const[status,setStatus]=useState(order.status);const[packed,setPacked]=useState(order.packed);const[note,setNote]=useState(order.adminNote??'');return <article className="admin-order"><div className="admin-order__top"><div><strong>{order.orderNumber}</strong><span>{new Date(order.createdAt).toLocaleString('he-IL')}</span></div><strong>₪{order.total}</strong></div><div className="admin-order__info"><span>{order.customer.fullName} · {order.customer.phone}</span><span>{order.distributionPoint.locality} — {order.distributionPoint.name}</span><span>{order.items.map(item=>`${item.productName} × ${item.quantity}`).join(', ')}</span><span>תשלום: {order.paymentMethod==='BIT'?'Bit':order.paymentMethod==='PAYBOX'?'PayBox':'תיאום לאחר ההזמנה'}</span></div><div className="admin-order__controls"><label>סטטוס<select value={status} onChange={(e)=>setStatus(e.target.value as OrderStatus)}>{statuses.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="packed-box"><input type="checkbox" checked={packed} onChange={(e)=>setPacked(e.target.checked)}/> נארזה</label><label className="admin-order__note">הערות<textarea value={note} onChange={(e)=>setNote(e.target.value)} rows={2}/></label><button className="button button--primary" onClick={()=>onSave(order,status,packed,note)}>שמירת עדכון</button></div></article>}
