import { useEffect, useState, type FormEvent } from 'react'
import { api } from '../services/api'
import type { Dashboard, Order, OrderStatus } from '../types/api'
import type { DistributionPoint } from '../types/distributionPoint'
import type { Product } from '../types/product'

type AdminDashboardProps = { credentials: string; points: DistributionPoint[]; products: Product[]; storeSlug: string; onProductAdded: () => void; onLogout: () => void }
type Section = 'home' | 'products' | 'orders'
type ProductInput = { name: string; description: string; category: string; imageUrl: string; price: string; available: boolean; maxQuantity: string }
const statuses: { value: OrderStatus; label: string }[] = [{ value: 'RECEIVED', label: 'התקבלה' }, { value: 'PREPARING', label: 'בהכנה' }, { value: 'READY_FOR_PICKUP', label: 'מוכנה לאיסוף' }, { value: 'DELIVERED', label: 'נמסרה' }, { value: 'CANCELLED', label: 'בוטלה' }]
const emptyProduct: ProductInput = { name: '', description: '', category: 'חסות ועלים ירוקים', imageUrl: '', price: '', available: true, maxQuantity: '' }

export function AdminDashboard({ credentials, points, products, storeSlug, onProductAdded, onLogout }: AdminDashboardProps) {
 const [section, setSection] = useState<Section>('home')
 const [orders, setOrders] = useState<Order[]>([]); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [filters, setFilters] = useState({ pickupPointId: '', productId: '', customerQuery: '', packed: '', status: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
 async function loadOrders() { setLoading(true); setError(''); try { const [nextOrders, nextDashboard] = await Promise.all([api.adminOrders(credentials, filters), api.dashboard(credentials, filters.pickupPointId)]); setOrders(nextOrders); setDashboard(nextDashboard) } catch { setError('לא ניתן לטעון את נתוני הניהול. ודאי שהשרת פעיל ושפרטי הכניסה נכונים.') } finally { setLoading(false) } }
 useEffect(() => { if (section === 'orders') void loadOrders() }, [section])
 async function saveOrder(order: Order, status: OrderStatus, packed: boolean, adminNote: string) { try { await api.updateOrder(credentials, order.id, status, packed, adminNote); await loadOrders() } catch { setError('שמירת ההזמנה נכשלה.') } }
 const heading = section === 'products' ? 'ניהול מוצרים' : section === 'orders' ? 'ניהול הזמנות' : 'ניהול המשק'
 return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">משק 32 · מנהל</p><h1>{heading}</h1></div><button className="button button--secondary" onClick={onLogout}>התנתקות</button></header>
 {section === 'home' && <section className="admin-menu"><button onClick={() => setSection('products')}><span>🥬</span><strong>מוצרים</strong><small>הוספה, שינוי, זמינות, הסרה והעלאת תמונה</small></button><button onClick={() => setSection('orders')}><span>📦</span><strong>הזמנות</strong><small>הזמנות, אריזה, הערות, סינון ומאזן</small></button></section>}
 {section === 'products' && <ProductManagement credentials={credentials} storeSlug={storeSlug} products={products} onBack={() => setSection('home')} onChanged={onProductAdded} />}
 {section === 'orders' && <><button className="back-link" onClick={() => setSection('home')}>→ חזרה לבחירת ניהול</button>{dashboard && <section className="admin-stats"><div><span>הזמנות</span><strong>{dashboard.totalOrders}</strong></div><div><span>נארזו</span><strong>{dashboard.packedOrders}</strong></div><div><span>פתוחות</span><strong>{dashboard.openOrders}</strong></div><div><span>סך הזמנות</span><strong>₪{dashboard.totalRevenue}</strong></div></section>}<section className="admin-filters"><label>נקודת איסוף<select value={filters.pickupPointId} onChange={(e) => setFilters({ ...filters, pickupPointId: e.target.value })}><option value="">הכול</option>{points.map(point => <option key={point.id} value={point.id}>{point.locality} — {point.name}</option>)}</select></label><label>מוצר<select value={filters.productId} onChange={(e) => setFilters({ ...filters, productId: e.target.value })}><option value="">הכול</option>{products.map(product => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>לקוח או טלפון<input value={filters.customerQuery} onChange={(e) => setFilters({ ...filters, customerQuery: e.target.value })} /></label><label>אריזה<select value={filters.packed} onChange={(e) => setFilters({ ...filters, packed: e.target.value })}><option value="">הכול</option><option value="true">נארז</option><option value="false">לא נארז</option></select></label><button className="button button--primary" onClick={() => void loadOrders()}>סינון</button></section>{error && <p className="form-error" role="alert">{error}</p>}{loading ? <p>טוען הזמנות…</p> : <section className="admin-orders">{orders.length === 0 ? <p>לא נמצאו הזמנות לפי הסינון שבחרת.</p> : orders.map(order => <AdminOrder key={order.id} order={order} onSave={saveOrder} />)}</section>}{dashboard && dashboard.byPickupPoint.length > 0 && <section className="pickup-summary"><h2>מאזן לפי נקודת איסוף</h2>{dashboard.byPickupPoint.map(point => <div key={point.distributionPointId}><span>{point.distributionPointName}</span><span>{point.orders} הזמנות · ₪{point.revenue}</span></div>)}</section>}</>}
 </main>
}

function ProductManagement({ credentials, storeSlug, products, onBack, onChanged }: { credentials: string; storeSlug: string; products: Product[]; onBack: () => void; onChanged: () => void }) {
 const [editing, setEditing] = useState<Product | null | undefined>(undefined); const [message, setMessage] = useState('')
 async function remove(product: Product) { if (!window.confirm(`להסיר את ${product.name} מהחנות?`)) return; try { await api.removeStoreProduct(credentials, storeSlug, product.id); setMessage('המוצר הוסר מהחנות.'); onChanged() } catch { setMessage('הסרת המוצר נכשלה.') } }
 async function toggle(product: Product) { try { await api.updateStoreProduct(credentials, storeSlug, product.id, { name: product.name, description: product.description, category: product.category || 'חסות ועלים ירוקים', imageUrl: product.imageUrl || '', price: product.price, available: !product.available, maxQuantity: product.maxQuantity }); setMessage(product.available ? 'המוצר סומן כלא זמין.' : 'המוצר סומן כזמין.'); onChanged() } catch { setMessage('שינוי הזמינות נכשל.') } }
 return <><button className="back-link" onClick={onBack}>→ חזרה לבחירת ניהול</button><section className="admin-products-header"><div><h2>קטלוג החנות</h2><p>כאן אפשר להוסיף, לערוך, להסתיר או להסיר מוצרים.</p></div><button className="button button--primary" onClick={() => setEditing(null)}>+ הוספת מוצר</button></section>{message && <p className={message.includes('נכשלה') ? 'form-error' : 'form-success'}>{message}</p>}{editing !== undefined && <ProductEditor key={editing?.id || 'new'} credentials={credentials} storeSlug={storeSlug} product={editing} onCancel={() => setEditing(undefined)} onSaved={(text) => { setMessage(text); setEditing(undefined); onChanged() }} />}<section className="admin-product-list">{products.map(product => <article key={product.id} className="admin-product"><div className="admin-product__image">{product.imageUrl ? <img src={product.imageUrl} alt="" /> : '🥬'}</div><div><strong>{product.name}</strong><span>₪{product.price} · {product.category}</span><small>{product.available ? 'זמין להזמנה' : 'לא זמין'}</small></div><div className="admin-product__actions"><button className="button button--secondary" onClick={() => setEditing(product)}>עריכה</button><button className="button button--secondary" onClick={() => void toggle(product)}>{product.available ? 'סימון כלא זמין' : 'סימון כזמין'}</button><button className="button button--danger" onClick={() => void remove(product)}>הסרה</button></div></article>)}</section></>
}

function ProductEditor({ credentials, storeSlug, product, onCancel, onSaved }: { credentials: string; storeSlug: string; product: Product | null; onCancel: () => void; onSaved: (message: string) => void }) {
 const initial: ProductInput = product ? { name: product.name, description: product.description, category: product.category || 'חסות ועלים ירוקים', imageUrl: product.imageUrl || '', price: String(product.price), available: product.available, maxQuantity: product.maxQuantity === null ? '' : String(product.maxQuantity) } : emptyProduct
 const [form, setForm] = useState<ProductInput>(initial); const [image, setImage] = useState<File | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
 async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); try { const imageUrl = image ? await api.uploadImage(credentials, image) : form.imageUrl; const input = { ...form, imageUrl, price: Number(form.price), maxQuantity: form.maxQuantity ? Number(form.maxQuantity) : null }; if (product) await api.updateStoreProduct(credentials, storeSlug, product.id, input); else await api.addStoreProduct(credentials, storeSlug, input); onSaved(product ? 'המוצר עודכן.' : 'המוצר נוסף לחנות.') } catch { setError('שמירת המוצר נכשלה. ודאי שכל השדות מלאים ושהתמונה עד 5MB.') } finally { setSaving(false) } }
 return <section className="admin-product-form"><div><p className="eyebrow">{product ? 'עריכת מוצר' : 'מוצר חדש'}</p><h2>{product ? product.name : 'הוספת מוצר'}</h2><p>בחירת תמונה מעלה אותה מהמחשב ישירות למאגר התמונות של האתר.</p></div><form onSubmit={submit}><label>שם מוצר<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>קטגוריה<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}><option>חסות ועלים ירוקים</option><option>מן הגינה</option></select></label><label>מחיר<input required type="number" min="0.01" step="0.01" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} /></label><label>מגבלת כמות<input type="number" min="1" value={form.maxQuantity} onChange={e => setForm({ ...form, maxQuantity: e.target.value })} /></label><label className="form-wide">תיאור<textarea required rows={2} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><label className="form-wide">תמונה מהמחשב<input type="file" accept="image/*" onChange={e => setImage(e.target.files?.[0] || null)} />{image && <small>נבחרה תמונה: {image.name}</small>}</label><label className="packed-box"><input type="checkbox" checked={form.available} onChange={e => setForm({ ...form, available: e.target.checked })} /> זמין להזמנה</label><div className="admin-form-actions"><button type="button" className="button button--secondary" onClick={onCancel}>ביטול</button><button className="button button--primary" disabled={saving}>{saving ? 'שומר…' : product ? 'שמירת שינויים' : 'הוספת מוצר'}</button></div>{error && <p className="form-error form-wide">{error}</p>}</form></section>
}

function AdminOrder({ order, onSave }: { order: Order; onSave: (order: Order, status: OrderStatus, packed: boolean, note: string) => void }) { const [status, setStatus] = useState(order.status); const [packed, setPacked] = useState(order.packed); const [note, setNote] = useState(order.adminNote ?? ''); return <article className="admin-order"><div className="admin-order__top"><div><strong>{order.orderNumber}</strong><span>{new Date(order.createdAt).toLocaleString('he-IL')}</span></div><strong>₪{order.total}</strong></div><div className="admin-order__info"><span>{order.customer.fullName} · {order.customer.phone}</span><span>{order.distributionPoint.locality} — {order.distributionPoint.name}</span><span>{order.items.map(item => `${item.productName} × ${item.quantity}`).join(', ')}</span><span>תשלום: {order.paymentMethod === 'BIT' ? 'Bit' : order.paymentMethod === 'PAYBOX' ? 'PayBox' : 'תיאום לאחר ההזמנה'}</span></div><div className="admin-order__controls"><label>סטטוס<select value={status} onChange={(e) => setStatus(e.target.value as OrderStatus)}>{statuses.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="packed-box"><input type="checkbox" checked={packed} onChange={(e) => setPacked(e.target.checked)} /> נארזה</label><label className="admin-order__note">הערות<textarea value={note} onChange={(e) => setNote(e.target.value)} rows={2} /></label><button className="button button--primary" onClick={() => onSave(order, status, packed, note)}>שמירת עדכון</button></div></article> }
